// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError =
  | { FileNotFound: string }
  | { Io: string }
  | { InvalidPath: string }
  | { PermissionDenied: string }
  | { FileAlreadyExists: string }
  | { InvalidMarkdown: string }
  | { Unknown: string };
