// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateNoteRequest = { path: string, title: string, content: string | null, };

export type Note = { path: string, title: string, content: string, size: bigint, createdAt: string | null, modifiedAt: string | null, };

export type NoteInfo = { path: string, title: string, size: bigint, modifiedAt: string | null, isDirectory: boolean, };
