// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateVaultRequest = {
  path: string;
  name: string;
  description: string | null;
};

export type RecentVault = {
  id: string;
  name: string;
  path: string;
  lastOpened: string;
};

export type Vault = {
  id: string;
  name: string;
  path: string;
  createdAt: string;
  lastOpened: string;
  noteCount: number;
  totalSize: bigint;
  config: VaultConfig;
};

export type VaultConfig = {
  name: string;
  description: string | null;
  settings: VaultSettings;
  metadata: { [key in string]?: string };
};

export type VaultInfo = {
  id: string;
  name: string;
  path: string;
  noteCount: number;
  totalSize: bigint;
  lastOpened: string;
  isCurrent: boolean;
};

export type VaultSettings = {
  autoSave: boolean;
  defaultNoteLocation: string;
  fileExtensions: Array<string>;
  excludePatterns: Array<string>;
};
